import "~/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { ToastProvider } from "src/components/providers/toaster-provider";

export const metadata: Metadata = {
  title: "UDEMY",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider> 
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <ToastProvider />
        {children}
        </body>
    </html>
    </ClerkProvider>
  );
}
